### ISSUE TITLE
418 server issue when put dob 

### ISSUE THREAD

**Issue by duyreus3105** [Wanchester/sd-back#20] opened 2022-08-24 04:37 UTC
<img width="1440" alt="Screen Shot 2022-08-16 at 11 59 11 pm" src="https://user-images.githubusercontent.com/67491445/186329891-b3751cd1-1473-41b8-975c-435e525f1f3d.png">

can not change the date of birth

**Comment by ethanqm** [comment] 2022-08-24 05:31
I think this is fixed now

**Comment by ethanqm** [comment] 2022-08-24 05:46
oops nvm

**Comment by ethanqm** [comment] 2022-08-24 06:40
Comment from that branch explaining the issue:
"""


EC2 said the error was that 'String.includes()' does not exist. It does in ES6 and (basically) therefore Typescript, however we transpile to ES5 and this case is (silently) not handled by Typescript.
I have replaced this function with a regular expression.

This problem may have been caused by my removal of the need for the --downLevelIteration flag when I changed [...string] to string.split('').

"""

**Closed as completed** 2022-08-29 05:48 UTC
